# This workflow validates, deploys, and runs the specified bundle
# within a production target named "prod".
name: 'Production deployment'

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a commit is pushed to the repo's main branch.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install uv, required to build python artifacts during bundle deploy.
      - uses: astral-sh/setup-uv@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "prod" target as defined in the bundle's settings file.
      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

  pipeline_update:
    name: 'Run pipeline update'
    runs-on: ubuntu-latest
    needs:
      - deploy

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install uv to run bundle tasks that build python artifacts.
      - uses: astral-sh/setup-uv@v3

      - uses: databricks/setup-cli@main

      # Run the Databricks workflow named "my-job" as defined in the bundle that was just deployed.
      - run: databricks bundle run dab_test_labs_job --refresh-all
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
